#config-version=FGT100F-7.4.4-FW-build2581-241015:opmode=0:vdom=0
#buildno=2581
config system global
    set hostname "FGT-OT-74"
    set admintimeout 30
    set strong-crypto enable
end
config firewall policy
    edit 1
        set name "internal-to-internet"
        set action accept
        set status enable
        set srcintf "lan"
        set dstintf "wan1"
        set srcaddr "internal-subnet"
        set dstaddr "all"
        set service "HTTPS" "HTTP"
        set av-profile "default"
        set ips-sensor "default"
        set logtraffic all
    next
end
