#config-version=FGT100F-7.2.8-FW-build1639-240412:opmode=0:vdom=0
config system global
    set hostname "FGT-POLICY-LAB"
end
config firewall address
    edit "SRV-WEB"
        set subnet 10.0.0.10 255.255.255.255
    next
    edit "NET-LAN"
        set subnet 192.168.1.0 255.255.255.0
    next
    edit "RANGE-DB"
        set type iprange
        set start-ip 10.0.1.5
        set end-ip 10.0.1.9
    next
    edit "EXT-FQDN"
        set type fqdn
        set fqdn "updates.example.com"
    next
    edit "GEO-CN"
        set type geography
        set country "CN"
    next
    edit "NET-BIG"
        set subnet 10.0.0.0 255.0.0.0
    next
    edit "NET-SMALL"
        set subnet 10.0.1.0 255.255.255.0
    next
end
config firewall addrgrp
    edit "GRP-SERVERS"
        set member "SRV-WEB" "RANGE-DB"
    next
end
config firewall service custom
    edit "WEB-8443"
        set tcp-portrange 8443
    next
    edit "APP-RANGE"
        set tcp-portrange 1000-2000
    next
end
config firewall service group
    edit "SVC-WEB"
        set member "HTTP" "HTTPS"
    next
end
config firewall vip
    edit "WEB-VIP"
        set extip 203.0.113.5
        set mappedip "10.0.0.10"
        set extport 443
        set mappedport 8443
    next
end
config firewall policy
    edit 1
        set name "Broad-HTTPS"
        set srcintf "any"
        set dstintf "any"
        set srcaddr "all"
        set dstaddr "all"
        set service "HTTPS"
        set action accept
        set schedule "always"
    next
    edit 2
        set name "Servers-HTTPS"
        set srcintf "lan"
        set dstintf "wan1"
        set srcaddr "GRP-SERVERS"
        set dstaddr "all"
        set service "HTTPS"
        set action accept
        set schedule "always"
    next
    edit 3
        set name "Inbound-VIP"
        set srcintf "wan1"
        set dstintf "lan"
        set srcaddr "all"
        set dstaddr "WEB-VIP"
        set service "HTTPS"
        set action accept
        set schedule "always"
    next
    edit 4
        set name "Deny-DB-SSH"
        set srcintf "lan"
        set dstintf "wan1"
        set srcaddr "NET-LAN"
        set dstaddr "RANGE-DB"
        set service "SSH"
        set action deny
        set schedule "always"
    next
    edit 5
        set name "Updates-FQDN"
        set srcintf "lan"
        set dstintf "wan1"
        set srcaddr "all"
        set dstaddr "EXT-FQDN"
        set service "HTTPS"
        set action accept
        set schedule "always"
    next
    edit 6
        set name "Big-HTTP"
        set srcintf "lan"
        set dstintf "wan1"
        set srcaddr "NET-BIG"
        set dstaddr "all"
        set service "HTTP"
        set action accept
        set schedule "always"
    next
    edit 7
        set name "Small-HTTP"
        set srcintf "lan"
        set dstintf "wan1"
        set srcaddr "NET-SMALL"
        set dstaddr "all"
        set service "HTTP"
        set action accept
        set schedule "always"
    next
end
